#!/bin/bash

# ============================================
# [Tap Name] [IP Addr] [BridgeName] [LXC_NAME]
# ============================================

pushd /proc/sys/net/bridge
for f in bridge-nf-*; do echo 0 > $f; done
popd

#./create tap-left  10.0.0.1 br-left  left
#./create tap-right 10.0.0.2 br-right right

sudo ./create  tap0-0 10.10.0.9  br-0-0     lxc0-0
sudo ./create  tap1-0 10.10.0.10 br-1-0     lxc1-0

#sudo ./create  tap0-0 10.10.0.1  br-0-0     lxc0-0
#sudo ./create  tap1-0 10.10.0.14 br-1-0     lxc1-0


#sudo ./create  tap-jer1 10.10.0.11 br-jer1     lxc-jer1
#sudo ./create  tap-jer2 10.10.0.12 br-jer2     lxc-jer2
#sudo ./destroy tap-jer1 br-jer1     lxc-jer1
#sudo ./destroy tap-jer2 br-jer2     lxc-jer2

#sudo ./destroy tap0-0           br-0-0      lxc0-0 
#sudo ./destroy tap1-0           br-1-0      lxc1-0 


# ==================================
# [Tap Name] [BridgeName] [LXC_NAME]
# ==================================

#./destroy tap-left  br-left  left
#./destroy tap-right br-right right


